AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DisCPUScaleoutPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties: 
      AutoScalingGroupName: !ImportValue DisAutoscalingGroup
      PolicyType: SimpleScaling
      AdjustmentType: ChangeInCapacity
      ScalingAdjustment: '1'
Outputs:
  DisCPUScaleoutPolicy:
    Value: !Ref DisCPUScaleoutPolicy
    Export:
      Name: DisCPUScaleoutPolicy